#pragma once
#include <cstdint>

namespace shaiya
{
    enum struct ItemEffect : uint8_t
    {
        HypnosisCure = 1,
        StunCure,
        SilenceCure,
        DarknessCure,
        StopCure,
        SlowCure,
        FaintProtection,
        DeathProtection,
        VenomCure,
        DiseaseCure,
        DisorderCure,
        ArcanePotion = 17,
        CurePotion,
        DispelPotion,
        AbolishingPotion,
        BlessingPotion,
        HolyPotion,
        PerfectCure = 26,
        GoddessBlessing = 30,
        PartyMemberSummon,
        PartyMemberMoveTo,
        SkillReset,
        StatReset,
        WarehouseRecall,
        LinkingHammer,
        Resurrection,
        MessageToServer,
        Teleportation,
        RepairHammer,
        TargetResurrection,
        ItemCreate,
        IncreaseFame,
        AppearanceChange,
        SexChange,
        Firework,
        CapitalRecall,
        BootleggeryRecall,
        ArenaRecall,
        ExpRemoval,
        NameChange,
        Etin1,
        Etin10,
        Etin100,
        Etin1000,
        GuildHouseRecall,
        GemAddItemProtect,
        ExtractionHammer,
        MoveWar,
        RecreationRune = 62,
        EnergyCrystal,
        EquipMale,
        EquipFemale,
        PerfectLinkingHammer = 69,
        MobGen = 73,
        PremiumLapisiaLv1 = 76,
        PremiumLapisiaLv2,
        PremiumLapisiaLv3,
        CrowleyEssence = 85,
        StrRecreationRune,
        DexRecreationRune,
        IntRecreationRune,
        WisRecreationRune,
        RecRecreationRune,
        LucRecreationRune,
        CrowleyLiquid,
        StrVial,
        DexVial,
        IntVial,
        WisVial,
        RecVial,
        LucVial,
        ChaoticSquare,
        DungeonMap,
        CraftingHammer = 102,
        LapisianAddItemProtect,
        TownMoveScroll,
        ItemAbilityTransfer,
        Catalyst,
        EnchantEnhancer,
        Dye = 110,
        HaloReactor,
        Spellbook,
        EternalContinuousResurrection,
        EternalPreventItemDrop,
        EternalPreventExpDrop,
        TyrosStone,
        AbsoluteRecreationRune,
        NpcRecall = 200,
        Item500 = 210,
        PetPickGoldDrop = 212,
        PetPickItemDrop,
        PetPickDrop
    };
}
